<a href="https://colab.research.google.com/github/ArthBachhuka123/MachineLearning/blob/main/Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv("customer.csv")

In [6]:
df.sample(5)

age  gender   review education purchased
21   32    Male  Average        PG        No
12   51    Male     Poor    School        No
40   39    Male     Good    School        No
3    72  Female     Good        PG        No
22   18  Female     Poor        PG       Yes

In [7]:
df = df.iloc[:,2:]

In [8]:
df

review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes
15     Poor        UG        No
16     Poor        UG       Yes
17     Poor        UG       Yes
18     Good    School        No
19     Poor        PG       Yes
20  Average    School       Yes
21  Average        PG        No
22     Poor        PG       Yes
23     Good    School        No
24  Average        PG       Yes
25     Good    School        No
26     Poor        PG        No
27     Poor        PG        No
28     Poor    School        No
29  Average        UG       Yes
30  Average        UG        No
31     Poor    School       Yes
32  Average        UG       Yes
33     Good        PG       Yes
34  Average    School        No
35     Poor    School       Yes
36     Good        UG       Yes
37  Average        PG       Yes
38     Good    School        No
39     Poor        PG        No
40     Good    School        No
41     Good        PG       Yes
42     Good        PG       Yes
43     Poor        PG        No
44  Average        UG        No
45     Poor        PG       Yes
46     Poor        PG        No
47     Good        PG       Yes
48     Good        UG       Yes
49     Good        UG        No

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df['purchased'],test_size=0.2)

In [11]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[["Poor","Average","Good"],["School","UG","PG"]])
oe.fit(X_train)
X_train = oe.transform(X_train)

In [12]:
X_train

array([[0., 0.],
       [0., 1.],
       [2., 2.],
       [1., 1.],
       [0., 2.],
       [1., 2.],
       [1., 1.],
       [2., 0.],
       [1., 2.],
       [0., 2.],
       [2., 0.],
       [0., 1.],
       [0., 2.],
       [1., 0.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [2., 1.],
       [1., 0.],
       [1., 0.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [2., 2.],
       [1., 1.],
       [2., 2.],
       [1., 1.],
       [2., 2.],
       [2., 0.]])

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y_train)
y_train = le.transform(y_train)

In [14]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [16]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [17]:
#### One hot encoding



In [33]:
df = pd.read_csv("/content/drive/MyDrive/files/cars.csv")

In [34]:
df.sample(5)

brand  km_driven    fuel        owner  selling_price
2404     Tata      20000  Petrol  First Owner         390000
2813   Maruti      10000  Petrol  First Owner         575000
4662     Tata     100000  Diesel  First Owner         490000
5293  Hyundai      40000  Petrol  First Owner         300000
6083    Honda      60000  Petrol  First Owner         265000

In [35]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df['selling_price'],test_size=0.2)

In [36]:
X_train

brand  km_driven    fuel        owner
2319   Hyundai       8000  Petrol  First Owner
7508      Audi      60000  Diesel  First Owner
5080    Maruti      80000  Petrol  Third Owner
3772     Honda      93500  Petrol  Third Owner
1636  Mahindra     110000  Diesel  First Owner
...        ...        ...     ...          ...
4265    Maruti       5621  Petrol  First Owner
988    Hyundai      60000  Petrol  First Owner
425      Honda       7032  Petrol  First Owner
5515     Honda      57900  Diesel  First Owner
7866     Honda      56494  Petrol  First Owner

[6502 rows x 4 columns]

In [37]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first',dtype=np.int32)
X_train_new = ohe.fit_transform(X_train[['fuel','owner']]).toarray()
X_test_new = ohe.transform(X_test[['fuel','owner']]).toarray()

In [38]:
X_train_new

array([[0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 1],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]], dtype=int32)

In [39]:
X_train

brand  km_driven    fuel        owner
2319   Hyundai       8000  Petrol  First Owner
7508      Audi      60000  Diesel  First Owner
5080    Maruti      80000  Petrol  Third Owner
3772     Honda      93500  Petrol  Third Owner
1636  Mahindra     110000  Diesel  First Owner
...        ...        ...     ...          ...
4265    Maruti       5621  Petrol  First Owner
988    Hyundai      60000  Petrol  First Owner
425      Honda       7032  Petrol  First Owner
5515     Honda      57900  Diesel  First Owner
7866     Honda      56494  Petrol  First Owner

[6502 rows x 4 columns]

In [40]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Hyundai', 8000, 0, ..., 0, 0, 0],
       ['Audi', 60000, 1, ..., 0, 0, 0],
       ['Maruti', 80000, 0, ..., 0, 0, 1],
       ...,
       ['Honda', 7032, 0, ..., 0, 0, 0],
       ['Honda', 57900, 1, ..., 0, 0, 0],
       ['Honda', 56494, 0, ..., 0, 0, 0]], dtype=object)

In [41]:
X_train

brand  km_driven    fuel        owner
2319   Hyundai       8000  Petrol  First Owner
7508      Audi      60000  Diesel  First Owner
5080    Maruti      80000  Petrol  Third Owner
3772     Honda      93500  Petrol  Third Owner
1636  Mahindra     110000  Diesel  First Owner
...        ...        ...     ...          ...
4265    Maruti       5621  Petrol  First Owner
988    Hyundai      60000  Petrol  First Owner
425      Honda       7032  Petrol  First Owner
5515     Honda      57900  Diesel  First Owner
7866     Honda      56494  Petrol  First Owner

[6502 rows x 4 columns]

In [42]:
from re import X
X_train_new.shape

(6502, 7)

In [43]:
X_train.shape

(6502, 4)

In [45]:
counts = df['brand'].value_counts()
df['brand'].nunique()
threshold = 100
repl = counts[counts <= threshold].index
pd.get_dummies(df['brand'].replace(repl, 'uncommon'))

BMW  Chevrolet   Ford  Honda  Hyundai  Mahindra  Maruti  Renault  \
0     False      False  False  False    False     False    True    False   
1     False      False  False  False    False     False   False    False   
2     False      False  False   True    False     False   False    False   
3     False      False  False  False     True     False   False    False   
4     False      False  False  False    False     False    True    False   
...     ...        ...    ...    ...      ...       ...     ...      ...   
8123  False      False  False  False     True     False   False    False   
8124  False      False  False  False     True     False   False    False   
8125  False      False  False  False    False     False    True    False   
8126  False      False  False  False    False     False   False    False   
8127  False      False  False  False    False     False   False    False   

      Skoda   Tata  Toyota  Volkswagen  uncommon  
0     False  False   False       False     False  
1      True  False   False       False     False  
2     False  False   False       False     False  
3     False  False   False       False     False  
4     False  False   False       False     False  
...     ...    ...     ...         ...       ...  
8123  False  False   False       False     False  
8124  False  False   False       False     False  
8125  False  False   False       False     False  
8126  False   True   False       False     False  
8127  False   True   False       False     False  

[8128 rows x 13 columns]

In [1]:
# Column transformer

In [2]:
import pandas as pd
import numpy as np


In [3]:
df = pd.read_csv("/content/drive/MyDrive/files/covid_toy.csv")

In [4]:
df.sample(5)

age  gender  fever   cough     city has_covid
93   27    Male  100.0    Mild  Kolkata       Yes
17   40  Female   98.0  Strong    Delhi        No
16   69  Female  103.0    Mild  Kolkata       Yes
31   83    Male  103.0    Mild  Kolkata        No
37   55    Male  100.0    Mild  Kolkata        No

In [5]:

# gender -> onehot
# fever -> simple imputer
# cough -> ordinal encoding
# city -> onehot

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder

In [13]:
transformer = ColumnTransformer(transformers=[
    ("tnf1",SimpleImputer(),['fever']),
    ("tnf2",OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ("tnf3",OneHotEncoder(drop='first',sparse_output=False),['gender','city'])
],remainder='passthrough'
)

In [14]:
transformer.fit_transform(X_train)
transformer.transform(X_test)

array([[104.  ,   1.  ,   0.  ,   0.  ,   1.  ,   0.  ,  54.  ],
       [100.  ,   0.  ,   1.  ,   0.  ,   0.  ,   0.  ,  80.  ],
       [101.  ,   1.  ,   0.  ,   1.  ,   0.  ,   0.  ,  68.  ],
       [100.  ,   1.  ,   0.  ,   0.  ,   0.  ,   0.  ,  19.  ],
       [ 98.  ,   0.  ,   1.  ,   0.  ,   0.  ,   0.  ,  73.  ],
       [100.  ,   0.  ,   1.  ,   1.  ,   0.  ,   0.  ,  27.  ],
       [101.  ,   1.  ,   0.  ,   0.  ,   1.  ,   0.  ,  51.  ],
       [100.75,   0.  ,   1.  ,   0.  ,   0.  ,   1.  ,  23.  ],
       [104.  ,   1.  ,   0.  ,   1.  ,   0.  ,   0.  ,  75.  ],
       [100.75,   0.  ,   1.  ,   1.  ,   0.  ,   0.  ,  38.  ],
       [103.  ,   0.  ,   1.  ,   0.  ,   1.  ,   0.  ,  83.  ],
       [ 98.  ,   1.  ,   0.  ,   0.  ,   1.  ,   0.  ,  10.  ],
       [103.  ,   0.  ,   0.  ,   0.  ,   1.  ,   0.  ,  50.  ],
       [103.  ,   1.  ,   1.  ,   0.  ,   0.  ,   0.  ,  46.  ],
       [104.  ,   0.  ,   1.  ,   0.  ,   1.  ,   0.  ,  16.  ],
       [ 98.  ,   1.  ,  